ALTER TABLE lessons ADD COLUMN guid TEXT NOT NULL DEFAULT '';
ALTER TABLE lessons ADD COLUMN source_show TEXT NOT NULL DEFAULT '';
ALTER TABLE lessons ADD COLUMN word_count INTEGER NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS idx_lessons_guid ON lessons(guid);

ALTER TABLE attempts ADD COLUMN user_transcript TEXT NOT NULL DEFAULT '';
ALTER TABLE attempts ADD COLUMN correct_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE attempts ADD COLUMN missing_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE attempts ADD COLUMN extra_count INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_attempts_lesson_id ON attempts(lesson_id);
